# Site settings
title: Mr Fred's Gins ðŸ¸
description: >- # this means to ignore newlines until "baseurl:"
  A modest collection of the finest thing juniper berries can become when they grow up.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author:
  name: Mr Fred
  url: https://gins.pw
  email: mrfred@gins.pw
twitter_username: fwenzel
github_username:  fwenzel

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
remote_theme: chesterhow/tale

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:    /:year-:month-:day/:title
paginate:     5

# Post defaults
defaults:
  -
    scope:
      path: ""
    values:
      author: "Mr Fred"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
